#!/usr/bin/env bun
/**
 * sync-angel-roku-ast-grep.ts
 *
 * Installs this repo's BrightScript / BrighterScript / SceneGraph ast-grep custom
 * languages into a peer Roku app, so ast-grep can search / lint / rewrite that
 * app's .brs/.bs/.xml with the same grammars this repo builds. Default target is
 * the sibling ../angel-roku.
 *
 *   bun scripts/sync-angel-roku-ast-grep.ts [targetDir] [--dry-run]
 *   ANGEL_ROKU_DIR=/path/to/app bun scripts/sync-angel-roku-ast-grep.ts
 *
 * What it does (idempotent):
 *   1. copy the 3 compiled tree-sitter parsers (.so) →
 *      <target>/.ast-grep/parsers/   (gitignored — platform-specific binaries)
 *   2. write a MANAGED <target>/sgconfig.yml registering the custom languages
 *      (brightscript/.brs, brighterscript/.bs, scenegraph/.xml) + the SceneGraph
 *      <script> language injections, libraryPath → the vendored .so
 *   3. ensure <target>/.gitignore ignores .ast-grep/parsers/
 *   4. ensure <target>/rules/ exists (the ruleDirs home for app-specific rules)
 *
 * The parsers are tree-sitter ABI15 and load with @ast-grep/cli ^0.42.3 — the
 * target must have a matching ast-grep installed (this script checks + warns; it
 * does NOT install it). sgconfig.yml is fully managed here (it carries a GENERATED
 * header); a re-run overwrites it only when that header is present, never a
 * hand-authored one. The .so are vendored (not referenced from this repo) so the
 * target's ast-grep works without this repo sitting beside it at scan time.
 */
import {
  cpSync,
  existsSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, resolve } from "node:path";

const REPO = resolve(import.meta.dir, "..");
const args = process.argv.slice(2);
const dryRun = args.includes("--dry-run");
const targetArg = args.find((a) => !a.startsWith("-"));
const TARGET = resolve(
  targetArg || process.env.ANGEL_ROKU_DIR || join(REPO, "..", "angel-roku"),
);

// Each compiled parser: source .so in this repo → vendored name in the target.
const PARSERS = [
  { lang: "brightscript", so: "tree-sitter-brightscript/brightscript.so", ext: "brs" },
  { lang: "brighterscript", so: "tree-sitter-brighterscript/brighterscript.so", ext: "bs" },
  { lang: "scenegraph", so: "tree-sitter-scenegraph/scenegraph.so", ext: "xml" },
] as const;

const PARSER_DIR_REL = ".ast-grep/parsers";
const SGCONFIG_REL = "sgconfig.yml";
const GITIGNORE_LINE = ".ast-grep/parsers/";
const GEN_MARKER = "GENERATED by ast-grep-brightscript";

const soName = (soPath: string) => soPath.slice(soPath.lastIndexOf("/") + 1);

const SGCONFIG = `# ${GEN_MARKER} (scripts/sync-angel-roku-ast-grep.ts) — managed file.
# Registers the BrightScript / BrighterScript / SceneGraph custom languages, backed
# by the vendored tree-sitter parsers under ${PARSER_DIR_REL}/ (gitignored, copied
# in by the sync). Re-sync from the ast-grep-brightscript repo:
#   npm run sync:angel-roku:ast-grep
# Add your own ast-grep rules under rules/ (ruleDirs below). Edits to THIS file are
# overwritten on the next sync — change them in ast-grep-brightscript instead.
ruleDirs:
  - rules
customLanguages:
${PARSERS.map(
  (p) =>
    `  ${p.lang}:\n    libraryPath: ${PARSER_DIR_REL}/${soName(p.so)}\n    extensions: [${p.ext}]`,
).join("\n")}
# BrightScript / BrighterScript are embedded in SceneGraph <script> bodies; reparse
# each region with the matching grammar (body kind chosen by the <script> type attr).
languageInjections:
  - hostLanguage: scenegraph
    rule:
      kind: BrightScriptBody
      pattern: $CONTENT
    injected: brightscript
  - hostLanguage: scenegraph
    rule:
      kind: BrighterScriptBody
      pattern: $CONTENT
    injected: brighterscript
`;

const log = (s: string) => console.log(s);
const warn = (s: string) => console.log(`⚠ ${s}`);
const fail = (s: string) => {
  console.error(`✖ ${s}`);
  process.exit(1);
};

// --- validate target ---------------------------------------------------------
if (!existsSync(TARGET)) fail(`target not found: ${TARGET}`);
log(`→ target: ${TARGET}${dryRun ? "  (dry run)" : ""}`);

// ast-grep must be present in the target for the .so to be usable. Warn (don't
// fail) so the sync still lays down config; the binary can be installed after.
const hasAstGrepModule = existsSync(
  join(TARGET, "node_modules", "@ast-grep", "cli"),
);
let declaresAstGrep = false;
const pkgPath = join(TARGET, "package.json");
if (existsSync(pkgPath)) {
  try {
    const pkg = JSON.parse(readFileSync(pkgPath, "utf8"));
    declaresAstGrep =
      !!pkg.devDependencies?.["@ast-grep/cli"] ||
      !!pkg.dependencies?.["@ast-grep/cli"];
  } catch {
    /* ignore — non-fatal */
  }
}
if (!hasAstGrepModule)
  warn(
    `@ast-grep/cli not installed in ${TARGET}.\n` +
      `  Install a matching version so the vendored ABI15 parsers load:\n` +
      `    npm install --save-dev @ast-grep/cli@^0.42.3 --prefix "${TARGET}"`,
  );
else if (!declaresAstGrep)
  warn("@ast-grep/cli is in node_modules but not in package.json devDependencies.");

// --- 1. copy the compiled parsers -------------------------------------------
for (const p of PARSERS) {
  const from = join(REPO, p.so);
  const to = join(TARGET, PARSER_DIR_REL, soName(p.so));
  if (!existsSync(from))
    fail(`missing parser: ${p.so} — build it first (see the grammar's README).`);
  log(`${dryRun ? "would copy" : "copy"}  ${p.so}  →  ${PARSER_DIR_REL}/${soName(p.so)}`);
  if (!dryRun) {
    mkdirSync(dirname(to), { recursive: true });
    cpSync(from, to);
  }
}

// --- 2. write the managed sgconfig.yml --------------------------------------
const sgPath = join(TARGET, SGCONFIG_REL);
if (existsSync(sgPath)) {
  const cur = readFileSync(sgPath, "utf8");
  if (!cur.includes(GEN_MARKER))
    fail(
      `${SGCONFIG_REL} already exists in the target and is NOT managed by this sync\n` +
        `  (no "${GEN_MARKER}" marker). Refusing to overwrite hand-authored config.\n` +
        `  Merge the customLanguages + languageInjections blocks manually, or remove\n` +
        `  the file and re-run to regenerate it.`,
    );
}
if (dryRun) {
  log(`would write  ${SGCONFIG_REL}  (managed: customLanguages + injections + ruleDirs)`);
} else {
  writeFileSync(sgPath, SGCONFIG);
  log(`write  ${SGCONFIG_REL}`);
}

// --- 3. ensure the parser dir is gitignored ---------------------------------
const giPath = join(TARGET, ".gitignore");
const gi = existsSync(giPath) ? readFileSync(giPath, "utf8") : "";
const giHas = gi
  .split(/\r?\n/)
  .some((l) => l.trim() === GITIGNORE_LINE || l.trim() === ".ast-grep/" || l.trim() === ".ast-grep");
if (giHas) {
  log(".gitignore  →  parser dir already ignored (no change)");
} else {
  log(`${dryRun ? "would add" : "add"}  ${GITIGNORE_LINE}  →  .gitignore`);
  if (!dryRun) {
    const sep = gi.length === 0 || gi.endsWith("\n") ? "" : "\n";
    writeFileSync(
      giPath,
      `${gi}${sep}\n# vendored ast-grep tree-sitter parsers (platform-specific; re-synced from ast-grep-brightscript)\n${GITIGNORE_LINE}\n`,
    );
  }
}

// --- 4. ensure the ruleDirs home exists -------------------------------------
const rulesKeep = join(TARGET, "rules", ".gitkeep");
if (existsSync(join(TARGET, "rules"))) {
  log("rules/  →  already present (no change)");
} else {
  log(`${dryRun ? "would create" : "create"}  rules/  (ruleDirs home)`);
  if (!dryRun) {
    mkdirSync(dirname(rulesKeep), { recursive: true });
    writeFileSync(rulesKeep, "");
  }
}

log(
  dryRun
    ? "\n✓ dry run complete — no files written."
    : "\n✓ synced. The BrightScript ast-grep custom languages are registered in the target.",
);
if (!dryRun)
  log(
    `  Verify in the target:\n` +
      `    npx ast-grep run -p '$X = $Y' --lang brightscript source/main.brs\n` +
      `    (or: npx ast-grep scan)`,
  );
